USE academico;

SET FOREIGN_KEY_CHECKS = 0;
drop table if exists aluno;
drop table if exists disciplina;
drop table if exists matricula;
drop table if exists professor;
drop table if exists turma;
SET FOREIGN_KEY_CHECKS = 1;

show tables;

CREATE TABLE ALUNO (
NOME VARCHAR(30) NOT NULL,
RA INT NOT NULL,
IDADE INT,
DATANASC DATE,
CONSTRAINT PK_ALUNO PRIMARY KEY (RA),
CONSTRAINT UN_NOME UNIQUE(NOME)
);

CREATE TABLE PROFESSOR (
NOME VARCHAR(30) NOT NULL UNIQUE,
NFUNC INT NOT NULL PRIMARY KEY,
IDADE INT,
TITULACAO CHAR(10) NOT NULL,
CONSTRAINT CH_TIT CHECK (TITULACAO IN ('MESTRE', 'DOUTOR', 'TITULAR')) #testar inserir com caixa baixa
);

CREATE TABLE DISCIPLINA (
SIGLA CHAR(6) NOT NULL,
NOME VARCHAR(30) NOT NULL,
NCRED INT NOT NULL,
PROFESSOR INT ,
LIVRO VARCHAR(30),
CONSTRAINT PK_DISCIPLINA PRIMARY KEY (SIGLA),
CONSTRAINT FK_DISCIPLINA FOREIGN KEY (PROFESSOR) REFERENCES
PROFESSOR(NFUNC) ON DELETE SET NULL,
CONSTRAINT NCREDITOS CHECK (NCRED > 0)
);

CREATE TABLE TURMA (
SIGLA CHAR(6) NOT NULL,
NUMERO INT NOT NULL,
NALUNOS INT NOT NULL
CHECK(NAlunos <= 70),
CONSTRAINT PK_TURMA PRIMARY KEY (SIGLA, NUMERO),
CONSTRAINT FK_TD FOREIGN KEY (SIGLA) REFERENCES DISCIPLINA(SIGLA)
ON DELETE CASCADE
);

CREATE TABLE MATRICULA (
SIGLA CHAR(6) NOT NULL,
NUMERO INT NOT NULL,
ALUNO INT NOT NULL,
ANO INT NOT NULL,
NOTA FLOAT,
CONSTRAINT PK_MAT PRIMARY KEY (SIGLA, NUMERO, ALUNO, ANO),
CONSTRAINT FK_MT FOREIGN KEY (SIGLA, NUMERO)
REFERENCES TURMA(SIGLA, NUMERO)
ON DELETE CASCADE,
CONSTRAINT FK_MA FOREIGN KEY (ALUNO) REFERENCES ALUNO(RA)
ON DELETE CASCADE
);

