--drop table aluno cascade constraints;
--drop table disciplina cascade constraints;
--drop table matricula cascade constraints;
--drop table professor cascade constraints;
--drop table turma cascade constraints;

CREATE TABLE ALUNO (
    NOME VARCHAR2(30) NOT NULL,
    NUSP NUMBER NOT NULL,
    IDADE NUMBER(3),
    DATANASC DATE,
    
    CONSTRAINT PK_ALUNO PRIMARY KEY (NUSP),
    CONSTRAINT UN_NOME UNIQUE(NOME)
);

CREATE TABLE PROFESSOR (
	NOME VARCHAR2(30) NOT NULL UNIQUE,
	NFUNC NUMBER NOT NULL PRIMARY KEY,
	IDADE NUMBER(3),
	TITULACAO CHAR(10) NOT NULL,

	CONSTRAINT CH_TIT CHECK (TITULACAO IN ('MESTRE', 'DOUTOR', 'TITULAR'))
);

CREATE TABLE DISCIPLINA (
	SIGLA CHAR(6) NOT NULL,
	NOME VARCHAR2(30) NOT NULL,
	NCRED NUMBER NOT NULL,
	PROFESSOR NUMBER ,
	LIVRO VARCHAR2(30),
	 CONSTRAINT PK_DISCIPLINA PRIMARY KEY (SIGLA),
	 CONSTRAINT FK_DISCIPLINA FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR(NFUNC) ON DELETE SET NULL,
	CONSTRAINT NCREDITOS CHECK (NCRED > 0)
);

CREATE TABLE TURMA (
    SIGLA CHAR(6) NOT NULL,
    NUMERO NUMBER NOT NULL,
    NALUNOS NUMBER NOT NULL
    CHECK(NAlunos <= 70),
    CONSTRAINT PK_TURMA PRIMARY KEY (SIGLA, NUMERO),
    CONSTRAINT FK_TD FOREIGN KEY (SIGLA) REFERENCES DISCIPLINA(SIGLA)
    ON DELETE CASCADE
);


CREATE TABLE MATRICULA (
	SIGLA CHAR(6) NOT NULL,
	NUMERO NUMBER NOT NULL,
	ALUNO NUMBER NOT NULL,
	ANO NUMBER(4) NOT NULL,
	NOTA FLOAT,
	CONSTRAINT PK_MAT PRIMARY KEY (SIGLA, NUMERO, ALUNO, ANO),
	CONSTRAINT FK_MT FOREIGN KEY (SIGLA, NUMERO)
    REFERENCES TURMA(SIGLA, NUMERO)
		ON DELETE CASCADE,
	CONSTRAINT FK_MA FOREIGN KEY (ALUNO) REFERENCES ALUNO(NUSP)
		ON DELETE CASCADE
);

