USE ACADEMICO;

SELECT * FROM ALUNO;

SELECT MAX(IDADE)
FROM ALUNO;

SELECT IDADE
FROM ALUNO
WHERE IDADE IN (SELECT MAX(IDADE) FROM ALUNO);


SELECT * FROM ALUNO;

SELECT * FROM disciplina;

SELECT * FROM MATRICULA;





SELECT A.NOME AS NOME_ALUNO, A.RA AS RA_ALUNO, D.NOME AS NOME_DISCIPLINA 
	FROM ALUNO A, DISCIPLINA D
    WHERE EXISTS (SELECT NULL FROM MATRICULA M WHERE M.ALUNO = A.RA)
    AND EXISTS (SELECT * FROM DISCIPLINA D WHERE D.MONITOR = A.RA)
	ORDER BY RA;





