USE ACADEMICO;

SELECT * FROM ALUNO;

SELECT * FROM MATRICULA;

SELECT *
FROM ALUNO, MATRICULA;

SELECT *
FROM ALUNO, MATRICULA
WHERE ALUNO.RA = MATRICULA.ALUNO;

SELECT *
FROM ALUNO INNER JOIN MATRICULA
ON ALUNO.RA = MATRICULA.ALUNO;



SELECT * FROM PROFESSOR;

SELECT * FROM DISCIPLINA;

DELETE FROM DISCIPLINA WHERE PROFESSOR = 33;

DELETE FROM DISCIPLINA WHERE PROFESSOR = 44;




SELECT *
FROM PROFESSOR INNER JOIN DISCIPLINA
ON PROFESSOR.NFUNC = DISCIPLINA.PROFESSOR;

SELECT *
FROM PROFESSOR LEFT OUTER JOIN DISCIPLINA
ON PROFESSOR.NFUNC = DISCIPLINA.PROFESSOR;

SELECT *
FROM PROFESSOR LEFT OUTER JOIN DISCIPLINA
ON PROFESSOR.NFUNC = DISCIPLINA.PROFESSOR
WHERE DISCIPLINA.PROFESSOR IS NULL;

SELECT *
FROM DISCIPLINA RIGHT OUTER JOIN PROFESSOR
ON PROFESSOR.NFUNC = DISCIPLINA.PROFESSOR;

#NÃO TEM FULL OUTER JOIN NO MYSQL - TEM QUE USAR UNION
SELECT *
FROM DISCIPLINA FULL OUTER JOIN PROFESSOR
ON PROFESSOR.NFUNC = DISCIPLINA.PROFESSOR;





SELECT *
FROM PROFESSOR LEFT OUTER JOIN DISCIPLINA
ON PROFESSOR.NFUNC = DISCIPLINA.PROFESSOR

UNION

SELECT *
FROM DISCIPLINA RIGHT OUTER JOIN PROFESSOR
ON PROFESSOR.NFUNC = DISCIPLINA.PROFESSOR;










